name: exam_app
description: "A new Flutter project."
publish_to: "none"

environment:
  sdk: ^3.11.0

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.9.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_secure_storage: ^10.0.0
  flutter_svg: ^2.2.4
  google_fonts: ^8.0.2
  injectable:
  get_it:
  json_annotation: ^4.9.0
  retrofit: ^4.9.0
  bloc: ^9.2.0
  equatable: ^2.0.8
  dart_either: ^2.1.0
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  injectable_generator:
  build_runner:
  json_serializable: ^6.10.0
  retrofit_generator: ^10.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

flutter_assets:
  assets_path: assets/
  output_path: lib/core/values/
  filename: images_paths.dart
  ignore_comments: true
